# -*- coding: utf-8 -*-
"""RLusingcybersecurity (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U05W1SgW5quwOas8NnOHL0oy1lmAXbgY
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras import regularizers
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics
pd.set_option('display.max_columns',None)
warnings.filterwarnings('ignore')
# %matplotlib inline

import zipfile
import os

# Step 1: Upload the file
uploaded = files.upload()

from google.colab import files
import zipfile
import pandas as pd
# Step 1: Upload the file
uploaded = files.upload()
# Assuming the uploaded file is 'nslkdd.zip'
zip_path = list(uploaded.keys())[0]

# Step 2: Unzip the file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall('extracted_files')

# Step 3: Read the KDDTrain+.txt file
train_data_path = 'extracted_files/KDDTrain+.txt'
data_train = pd.read_csv(train_data_path)

print(data_train.head())

columns = (['duration','protocol_type','service','flag','src_bytes','dst_bytes','land','wrong_fragment','urgent','hot'
,'num_failed_logins','logged_in','num_compromised','root_shell','su_attempted','num_root','num_file_creations'
,'num_shells','num_access_files','num_outbound_cmds','is_host_login','is_guest_login','count','srv_count','serror_rate'
,'srv_serror_rate','rerror_rate','srv_rerror_rate','same_srv_rate','diff_srv_rate','srv_diff_host_rate','dst_host_count','dst_host_srv_count'
,'dst_host_same_srv_rate','dst_host_diff_srv_rate','dst_host_same_src_port_rate','dst_host_srv_diff_host_rate','dst_host_serror_rate'
,'dst_host_srv_serror_rate','dst_host_rerror_rate','dst_host_srv_rerror_rate','outcome','level'])

# Assign name for columns
data_train.columns = columns

data_train.head()

data_train.info()

data_train.describe().style.background_gradient(cmap='Blues').set_properties(**{'font-family':'Segoe UI'})

data_train.loc[data_train['outcome'] == "normal", "outcome"] = 'normal'
data_train.loc[data_train['outcome'] != 'normal', "outcome"] = 'attack'

def pie_plot(df, cols_list, rows, cols):
    fig, axes = plt.subplots(rows, cols)
    for ax, col in zip(axes.ravel(), cols_list):
        df[col].value_counts().plot(ax=ax, kind='pie', figsize=(15, 15), fontsize=10, autopct='%1.0f%%')
        ax.set_title(str(col), fontsize = 12)
    plt.show()

pie_plot(data_train, ['protocol_type', 'outcome'], 1, 2)

def Scaling(df_num, cols):
    std_scaler = RobustScaler()
    std_scaler_temp = std_scaler.fit_transform(df_num)
    std_df = pd.DataFrame(std_scaler_temp, columns =cols)
    return std_df

cat_cols = ['is_host_login','protocol_type','service','flag','land', 'logged_in','is_guest_login', 'level', 'outcome']
def preprocess(dataframe):
    df_num = dataframe.drop(cat_cols, axis=1)
    num_cols = df_num.columns
    scaled_df = Scaling(df_num, num_cols)

    dataframe.drop(labels=num_cols, axis="columns", inplace=True)
    dataframe[num_cols] = scaled_df[num_cols]

    dataframe.loc[dataframe['outcome'] == "normal", "outcome"] = 0
    dataframe.loc[dataframe['outcome'] != 0, "outcome"] = 1

    dataframe = pd.get_dummies(dataframe, columns = ['protocol_type', 'service', 'flag'])
    return dataframe

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
import tensorflow as tf
from tensorflow.keras import layers, models
from collections import deque

import random
# Step 3: Read the KDDTrain+.txt and KDDTest+.txt files
train_data_path = 'extracted_files/KDDTrain+.txt'
test_data_path = 'extracted_files/KDDTest+.txt'

# Specify the column names
columns = (['duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
            'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell', 'su_attempted', 'num_root', 'num_file_creations',
            'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login', 'is_guest_login', 'count', 'srv_count',
            'serror_rate', 'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate',
            'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count', 'dst_host_same_srv_rate', 'dst_host_diff_srv_rate',
            'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate',
            'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'outcome', 'level'])

# Load the datasets with specified column names
data_train = pd.read_csv(train_data_path, names=columns, header=None)
data_test = pd.read_csv(test_data_path, names=columns, header=None)

# Preview the data
print("Training Data:")
print(data_train.head())
print("\nTesting Data:")
print(data_test.head())

# Preprocessing function
def preprocess_data(data):
    # One-hot encode categorical features
    categorical_features = ['protocol_type', 'service', 'flag']
    data = pd.get_dummies(data, columns=categorical_features)

    # Scale numerical features
    numerical_features = data.columns.difference(['outcome', 'level'])  # Exclude target columns
    scaler = StandardScaler()
    data[numerical_features] = scaler.fit_transform(data[numerical_features])

    return data

# Preprocess training and testing data
data_train = preprocess_data(data_train)
data_test = preprocess_data(data_test)

# Prepare features and targets
X_train = data_train.drop(['outcome', 'level'], axis=1).values
y_train = pd.get_dummies(data_train['outcome']).values
X_test = data_test.drop(['outcome', 'level'], axis=1).values
y_test = pd.get_dummies(data_test['outcome']).values

# DDQN Agent Class
class DDQNAgent:
    def __init__(self, state_size, action_size):
        self.state_size = state_size
        self.action_size = action_size
        self.memory = deque(maxlen=2000)
        self.gamma = 0.95  # Discount rate
        self.epsilon = 1.0  # Exploration rate
        self.epsilon_min = 0.01
        self.epsilon_decay = 0.995
        self.model = self._build_model()
        self.target_model = self._build_model()
        self.update_target_model()

    def _build_model(self):
        model = models.Sequential()
        model.add(layers.Dense(64, input_dim=self.state_size, activation='relu'))
        model.add(layers.Dense(32, activation='relu'))
        model.add(layers.Dense(self.action_size, activation='linear'))
        model.compile(loss='mse', optimizer=tf.keras.optimizers.Adam(learning_rate=0.001))  # Updated here
        return model

    def update_target_model(self):
        self.target_model.set_weights(self.model.get_weights())

    def remember(self, state, action, reward, next_state, done):
        self.memory.append((state, action, reward, next_state, done))

    def act(self, state):
        if np.random.rand() <= self.epsilon:
            return random.randrange(self.action_size)
        q_values = self.model.predict(state)
        return np.argmax(q_values[0])

    def replay(self, batch_size):
        minibatch = random.sample(self.memory, batch_size)
        for state, action, reward, next_state, done in minibatch:
            target = reward
            if not done:
                target += self.gamma * np.amax(self.target_model.predict(next_state)[0])
            target_f = self.model.predict(state)
            target_f[0][action] = target
            self.model.fit(state, target_f, epochs=1, verbose=0)
        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay

# Training the agent
def train_agent(episodes):
    agent = DDQNAgent(state_size=X_train.shape[1], action_size=y_train.shape[1])
    batch_size = 32

    for e in range(episodes):
        for i in range(len(X_train)):
            state = X_train[i].reshape(1, -1)
            action = agent.act(state)
            reward = 1 if np.argmax(y_train[i]) == action else -1
            next_state = X_train[i].reshape(1, -1)
            done = i == len(X_train) - 1
            agent.remember(state, action, reward, next_state, done)
            if len(agent.memory) > batch_size:
                agent.replay(batch_size)
        agent.update_target_model()
        print(f"Episode {e+1}/{episodes} completed.")

# Evaluate the agent
def evaluate_agent(agent):
    correct_predictions = 0
    predictions = []
    for i in range(len(X_test)):
        state = X_test[i].reshape(1, -1)
        action = agent.act(state)
        predictions.append(action)
        if np.argmax(y_test[i]) == action:
            correct_predictions += 1
    accuracy = correct_predictions / len(X_test)
    print(f"Test Accuracy: {accuracy * 100:.2f}%")

    # Detailed metrics
    print("Classification Report:")
    print(classification_report(np.argmax(y_test, axis=1), predictions))
    print("Confusion Matrix:")
    print(confusion_matrix(np.argmax(y_test, axis=1), predictions))

# Train the agent
train_agent(episodes=100)  # Adjust the number of episodes as needed

# Evaluate the agent
evaluate_agent(agent)

# Step 3: Read the KDDTrain+.txt and KDDTest+.txt files
train_data_path = 'extracted_files/KDDTrain+.txt'
test_data_path = 'extracted_files/KDDTest+.txt'

# Specify the column names
columns = (['duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
            'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell', 'su_attempted', 'num_root', 'num_file_creations',
            'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login', 'is_guest_login', 'count', 'srv_count',
            'serror_rate', 'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate',
            'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count', 'dst_host_same_srv_rate', 'dst_host_diff_srv_rate',
            'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate',
            'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'outcome', 'level'])

# Load the datasets with specified column names
data_train = pd.read_csv(train_data_path, names=columns, header=None)
data_test = pd.read_csv(test_data_path, names=columns, header=None)

# Preprocessing function
def preprocess_data(data):
    # One-hot encode categorical features
    categorical_features = ['protocol_type', 'service', 'flag']
    data = pd.get_dummies(data, columns=categorical_features)

    # Scale numerical features
    numerical_features = data.columns.difference(['outcome', 'level'])  # Exclude target columns
    scaler = StandardScaler()
    data[numerical_features] = scaler.fit_transform(data[numerical_features])

    return data

# Preprocess training and testing data
data_train = preprocess_data(data_train)
data_test = preprocess_data(data_test)

# Prepare features and targets
X_train = data_train.drop(['outcome', 'level'], axis=1).values
y_train = pd.get_dummies(data_train['outcome']).values
X_test = data_test.drop(['outcome', 'level'], axis=1).values
y_test = pd.get_dummies(data_test['outcome']).values

# DDQN Agent Class
class DDQNAgent:
    def __init__(self, state_size, action_size):
        self.state_size = state_size
        self.action_size = action_size
        self.memory = deque(maxlen=2000)
        self.gamma = 0.95  # Discount rate
        self.epsilon = 1.0  # Exploration rate
        self.epsilon_min = 0.01
        self.epsilon_decay = 0.995
        self.model = self._build_model()
        self.target_model = self._build_model()
        self.update_target_model()

    def _build_model(self):
        model = models.Sequential()
        model.add(layers.Dense(128, input_dim=self.state_size, activation='relu'))
        model.add(layers.Dropout(0.2))  # Dropout layer to prevent overfitting
        model.add(layers.Dense(64, activation='relu'))
        model.add(layers.Dropout(0.2))  # Another dropout layer
        model.add(layers.Dense(self.action_size, activation='linear'))
        model.compile(loss='mse', optimizer=tf.keras.optimizers.Adam(learning_rate=0.001))
        return model

    def update_target_model(self):
        self.target_model.set_weights(self.model.get_weights())

    def remember(self, state, action, reward, next_state, done):
        self.memory.append((state, action, reward, next_state, done))

    def act(self, state):
        if np.random.rand() <= self.epsilon:
            return random.randrange(self.action_size)
        q_values = self.model.predict(state)
        return np.argmax(q_values[0])

    def replay(self, batch_size):
        minibatch = random.sample(self.memory, batch_size)
        for state, action, reward, next_state, done in minibatch:
            target = reward
            if not done:
                target += self.gamma * np.amax(self.target_model.predict(next_state)[0])
            target_f = self.model.predict(state)
            target_f[0][action] = target
            self.model.fit(state, target_f, epochs=1, verbose=0)
        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay

# Training the agent
def train_agent(episodes):
    agent = DDQNAgent(state_size=X_train.shape[1], action_size=y_train.shape[1])
    batch_size = 32

    for e in range(episodes):
        for i in range(len(X_train)):
            state = X_train[i].reshape(1, -1)
            action = agent.act(state)
            reward = 1 if np.argmax(y_train[i]) == action else -1
            next_state = X_train[i].reshape(1, -1)
            done = i == len(X_train) - 1
            agent.remember(state, action, reward, next_state, done)
            if len(agent.memory) > batch_size:
                agent.replay(batch_size)
        agent.update_target_model()
        print(f"Episode {e+1}/{episodes} completed.")

# Evaluate the agent
def evaluate_agent(agent):
    correct_predictions = 0
    predictions = []
    for i in range(len(X_test)):
        state = X_test[i].reshape(1, -1)
        action = agent.act(state)
        predictions.append(action)
        if np.argmax(y_test[i]) == action:
            correct_predictions += 1
    accuracy = correct_predictions / len(X_test)
    print(f"Test Accuracy: {accuracy * 100:.2f}%")

    # Detailed metrics
    print("Classification Report:")
    print(classification_report(np.argmax(y_test, axis=1), predictions))
    print("Confusion Matrix:")
    print(confusion_matrix(np.argmax(y_test, axis=1), predictions))

# Train the agent
train_agent(episodes=100)  # Adjust the number of episodes as needed

# Evaluate the agent
evaluate_agent(agent)

from google.colab import files
import zipfile
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
import tensorflow as tf
from tensorflow.keras import layers, models
from collections import deque
import random
from sum_tree import SumTree

# Step 1: Upload the file
uploaded = files.upload()

# Step 2: Unzip the file
zip_path = list(uploaded.keys())[0]
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall('extracted_files')

# Step 3: Read the KDDTrain+.txt and KDDTest+.txt files
train_data_path = 'extracted_files/KDDTrain+.txt'
test_data_path = 'extracted_files/KDDTest+.txt'

# Specify the column names
columns = (['duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
            'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell', 'su_attempted', 'num_root', 'num_file_creations',
            'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login', 'is_guest_login', 'count', 'srv_count',
            'serror_rate', 'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate',
            'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count', 'dst_host_same_srv_rate', 'dst_host_diff_srv_rate',
            'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate',
            'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'outcome', 'level'])

# Load the datasets with specified column names
data_train = pd.read_csv(train_data_path, names=columns, header=None)
data_test = pd.read_csv(test_data_path, names=columns, header=None)

# Preprocessing function
def preprocess_data(data):
    # One-hot encode categorical features
    categorical_features = ['protocol_type', 'service', 'flag']
    data = pd.get_dummies(data, columns=categorical_features)

    # Scale numerical features
    numerical_features = data.columns.difference(['outcome', 'level'])  # Exclude target columns
    scaler = StandardScaler()
    data[numerical_features] = scaler.fit_transform(data[numerical_features])

    return data

# Preprocess training and testing data
data_train = preprocess_data(data_train)
data_test = preprocess_data(data_test)

# Prepare features and targets
X_train = data_train.drop(['outcome', 'level'], axis=1).values
y_train = pd.get_dummies(data_train['outcome']).values
X_test = data_test.drop(['outcome', 'level'], axis=1).values
y_test = pd.get_dummies(data_test['outcome']).values

# Prioritized Experience Replay
class PrioritizedReplayBuffer:
    def __init__(self, capacity):
        self.tree = SumTree(capacity)
        self.capacity = capacity

    def store(self, experience):
        max_priority = np.max(self.tree.tree[-self.tree.capacity:])
        if max_priority == 0:
            max_priority = 1
        self.tree.add(max_priority, experience)

    def sample(self, n):
        batch = []
        idxs = []
        segment = self.tree.total() / n
        priorities = []

        for i in range(n):
            a = segment * i
            b = segment * (i + 1)

            s = random.uniform(a, b)
            (idx, p, data) = self.tree.get(s)
            batch.append(data)
            idxs.append(idx)
            priorities.append(p)

        return batch, idxs, np.array(priorities)

    def update(self, idx, priority):
        self.tree.update(idx, priority)

# Dueling DQN Agent
class DuelingDQNAgent:
    def __init__(self, state_size, action_size):
        self.state_size = state_size
        self.action_size = action_size
        self.memory = PrioritizedReplayBuffer(capacity=50000)
        self.gamma = 0.95  # Discount rate
        self.epsilon = 1.0  # Exploration rate
        self.epsilon_min = 0.01
        self.epsilon_decay = 0.995
        self.model = self._build_model()
        self.target_model = self._build_model()
        self.update_target_model()

    def _build_model(self):
        # Dueling architecture
        state_input = layers.Input(shape=(self.state_size,))
        x = layers.Dense(128, activation='relu')(state_input)
        x = layers.Dropout(0.2)(x)
        x = layers.Dense(64, activation='relu')(x)
        x = layers.Dropout(0.2)(x)

        state_value = layers.Dense(1, activation='linear')(x)
        action_advantage = layers.Dense(self.action_size, activation='linear')(x)

        output = layers.Lambda(lambda a: a[0] + a[1] - tf.reduce_mean(a[1], keepdims=True), output_shape=(self.action_size,))([state_value, action_advantage])

        model = models.Model(inputs=state_input, outputs=output)
        model.compile(loss='mse', optimizer=tf.keras.optimizers.Adam(learning_rate=0.001))
        return model

    def update_target_model(self):
        self.target_model.set_weights(self.model.get_weights())

    def remember(self, state, action, reward, next_state, done):
        experience = (state, action, reward, next_state, done)
        self.memory.store(experience)

    def act(self, state):
        if np.random.rand() <= self.epsilon:
            return random.randrange(self.action_size)
        q_values = self.model.predict(state)
        return np.argmax(q_values[0])

    def replay(self, batch_size, beta):
        batch, idxs, priorities = self.memory.sample(batch_size)
        states = np.array([x[0] for x in batch])
        actions = np.array([x[1] for x in batch])
        rewards = np.array([x[2] for x in batch])
        next_states = np.array([x[3] for x in batch])
        dones = np.array([x[4] for x in batch])

        target_q_values = self.target_model.predict(next_states)
        max_target_q_values = np.amax(target_q_values, axis=1)
        y_target = rewards + (1 - dones) * self.gamma * max_target_q_values

        q_values = self.model.predict(states)
        q_values[np.arange(batch_size), actions] = y_target

        td_errors = np.abs(y_target - q_values[np.arange(batch_size), actions])
        for i in range(batch_size):
            idx = idxs[i]
            self.memory.update(idx, td_errors[i])

        loss = self.model.train_on_batch(states, q_values)

        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay

        return loss

# Training the agent
def train_agent(episodes, batch_size, beta):
    agent = DuelingDQNAgent(state_size=X_train.shape[1], action_size=y_train.shape[1])

    for e in range(episodes):
        state = X_train[0].reshape(1, -1)
        for i in range(len(X_train)):
            action = agent.act(state)
            reward = 1 if np.argmax(y_train[i]) == action else -1
            next_state = X_train[i].reshape(1, -1)
            done = i == len(X_train) - 1
            agent.remember(state, action, reward, next_state, done)
            state = next_state
            if len(agent.memory.tree) > batch_size:
                loss = agent.replay(batch_size, beta)
                print(f"Episode {e+1}/{episodes}, Step {i+1}/{len(X_train)}, Loss: {loss:.4f}")
        agent.update_target_model()

# Evaluate the agent
def evaluate_agent(agent):
    correct_predictions = 0
    predictions = []
    for i in range(len(X_test)):
        state = X_test[i].reshape(1, -1)
        action = agent.act(state)
        predictions.append(action)
        if np.argmax(y_test[i]) == action:
            correct_predictions += 1
    accuracy = correct_predictions / len(X_test)
    print(f"Test Accuracy: {accuracy * 100:.2f}%")

    # Detailed metrics
    print("Classification Report:")
    print(classification_report(np.argmax(y_test, axis=1), predictions))
    print("Confusion Matrix:")
    print(confusion_matrix(np.argmax(y_test, axis=1), predictions))

# Train the agent
train_agent(episodes=100, batch_size=32, beta=0.4)  # Adjust the number of episodes and hyperparameters as needed

# Evaluate the agent
evaluate_agent(agent)